### ISSUE TITLE
亦诗杯随机肉鸽邀请

### ISSUE THREAD

**Issue by s-yh-china** [SonodaHanami/ganbouki#1]
我们是魔法刺猬目录的粉丝和房管和建筑举办的随机肉鸽比赛，现在我们想制作一个兼骰子计分板和报名一体的网站。但是因为没有前端作者，所以我们通过刺猬直播找到了您。如果您有兴趣的话，您可以来我们的qq群618516293。XD

**Comment by SonodaHanami** [comment]
来了来了
